### ISSUE TITLE
Error with IE 11

### ISSUE THREAD

**Issue by bbehling** [SVoyt/esri-leaflet-dynamic-advanced#6]
Getting an error with this plugin in IE 11 "Object doesn't support property or method 'sign'". 

Works fine in Chrome.

```
var layer = new L.esri.dynamicMapLayerAdvanced({
                            url: url,
                            f: "image",
                            layers: [1,2,3],
                            pane: 'myMapPane'
                        }).addTo(map);
```

TypeError: Object doesn't support property or method 'sign'
   at _buildExportParams (http://localhost/LandStudio.Web/Scripts/esri-leaflet-dynamic-advanced.js:454:9)
   at _update (http://localhost/LandStudio.Web/Scripts/esri-leaflet-dynamic-advanced.js:401:9)
   at s (http://localhost/LandStudio.Web/Scripts/leaflet.js:5:909)
   at onAdd (http://localhost/LandStudio.Web/Scripts/esri-leaflet-dynamic-advanced.js:35:13)
   at _layerAdd (http://localhost/LandStudio.Web/Scripts/leaflet.js:6:9376)
   at whenReady (http://localhost/LandStudio.Web/Scripts/leaflet.js:6:4523)
   at addLayer (http://localhost/LandStudio.Web/Scripts/leaflet.js:6:9598)
   at addTo (http://localhost/LandStudio.Web/Scripts/leaflet.js:6:8693)
   at Anonymous function (http://localhost/LandStudio.Web/App/Modules/GeoSpatial/Leaflet-Components/MapComponent/MapComponent.js:56:25)
   at q (http://localhost/LandStudio.Web/Scripts/angular.min.js:8:1) Possibly unhandled rejection: {"description":"Object doesn't support property or method 'sign'","nu

**Comment by SVoyt** [comment]
Hmmm.... Do you use latest version?
Because of #5

**Comment by bbehling** [comment]
New version fixes the issue. Thanks
